### ISSUE TITLE
Chapter 11 - adversarial_attack.ipynb - cannot import name 'inspect' from 'torch_snippets.torch_loader'

### ISSUE THREAD

**Issue by jdvandenberg** [PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E#11]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 2
      1 get_ipython().run_line_magic('pip', 'install torch_snippets')
----> 2 from torch_snippets.torch_loader import inspect, show, np, torch, nn
      3 from torchvision.models import resnet50
      4 model = resnet50(pretrained=True)

ImportError: cannot import name 'inspect' from 'torch_snippets.torch_loader' (/opt/anaconda3/lib/python3.11/site-packages/torch_snippets/torch_loader.py)

**Comment by sizhky** [comment]
```
from torch_snippets.inspector import inspect
```
